// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGPcPfkfLs-IDjdQrLX0z-CFbvcCziYAE',
    appId: '1:457917083523:web:d65b333485b2b7b9ced0b6',
    messagingSenderId: '457917083523',
    projectId: 'mobyte-flight',
    authDomain: 'mobyte-flight.firebaseapp.com',
    storageBucket: 'mobyte-flight.appspot.com',
    measurementId: 'G-784ZYLQH6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxIrb3rsjFnMWrzUhZNc7oP6G-o_2iGA',
    appId: '1:457917083523:android:e1b7051bad8cf450ced0b6',
    messagingSenderId: '457917083523',
    projectId: 'mobyte-flight',
    storageBucket: 'mobyte-flight.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtofteinlTrNix8MLQprKZrIuLRQ4rrxE',
    appId: '1:457917083523:ios:15c7b239e3e03670ced0b6',
    messagingSenderId: '457917083523',
    projectId: 'mobyte-flight',
    storageBucket: 'mobyte-flight.appspot.com',
    iosClientId: '457917083523-hhn6cts3api2qk5s82327dpqtgh2kdn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobyteFlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtofteinlTrNix8MLQprKZrIuLRQ4rrxE',
    appId: '1:457917083523:ios:0fbfa37a3f8c8bc6ced0b6',
    messagingSenderId: '457917083523',
    projectId: 'mobyte-flight',
    storageBucket: 'mobyte-flight.appspot.com',
    iosClientId: '457917083523-00fsrs7l1388sgr7cra9fm1alrveqqgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobyteFlight.RunnerTests',
  );
}
